sudo: false

os:
  - linux

### Below code needed to solve https://github.com/Microsoft/vscode/issues/33998
addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run-script linter
